pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
  - name: docker
    image: docker:24.0.5-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
  - name: gradle
    image: eclipse-temurin:21-jdk-alpine
    command: ['sh', '-c', 'sleep 99d']
  volumes:
  - name: docker-sock
    emptyDir: {}
"""
    }
  }
  environment {
    DOCKER_IMAGE = 'julianmotta07/circle-guard-promotion'
    NAMESPACE   = 'circle-guard-dev'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Unit Tests') {
      steps {
        container('gradle') {
          sh './gradlew :services:circleguard-promotion-service:test'
        }
      }
      post { always {
        junit '**/build/test-results/test/*.xml'
      }}
    }
    stage('Build JAR') {
      steps {
        container('gradle') {
          sh './gradlew :services:circleguard-promotion-service:bootJar -x test'
        }
      }
    }
    stage('Build & Push Docker') {
      steps {
        container('docker') {
          withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials',
            usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
            sh 'docker build -t $DOCKER_IMAGE:dev-${BUILD_NUMBER} -f services/circleguard-promotion-service/Dockerfile .'
            sh 'docker push $DOCKER_IMAGE:dev-${BUILD_NUMBER}'
            sh 'docker tag $DOCKER_IMAGE:dev-${BUILD_NUMBER} $DOCKER_IMAGE:latest'
            sh 'docker push $DOCKER_IMAGE:latest'
          }
        }
      }
    }
    stage('Deploy to DEV') {
      steps {
        container('gradle') {
          sh """
            # Instalar curl primero (la imagen alpine no lo trae)
            apk add --no-cache curl
            
            # Instalar kubectl
            curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/kubectl
            
            # Desplegar en GKE
            kubectl set image deployment/promotion-service promotion-service=${DOCKER_IMAGE}:dev-${BUILD_NUMBER} -n ${NAMESPACE}
            kubectl rollout status deployment/promotion-service -n ${NAMESPACE}
          """
        }
      }
    }
  }
  post {
    success { echo 'Pipeline DEV promotion-service completado exitosamente' }
    failure { echo 'Pipeline DEV promotion-service fallido' }
  }
}